\encoding UTF8

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS users (
  user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fullname TEXT NOT NULL,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'user',
  status BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS home_config (
  id INT PRIMARY KEY DEFAULT 1,
  data JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
INSERT INTO home_config (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS articles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  image_url TEXT,
  badge TEXT NOT NULL DEFAULT 'ข่าวเกม',
  published_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Seed admin
INSERT INTO users (fullname, username, password, role, status)
VALUES ('Admin', 'admin', crypt('admin123', gen_salt('bf')), 'admin', TRUE)
ON CONFLICT (username) DO NOTHING;

-- Seed บทความเกม 30 รายการ
INSERT INTO articles (slug, title, content, image_url, badge, published_at) VALUES
  ('starfall-odyssey', 'Starfall Odyssey เปิดตัวเกม RPG แฟนตาซีอวกาศ', '<p>Starfall Odyssey เปิดตัวเกม RPG แฟนตาซีอวกาศ — รวมรายละเอียดเบื้องต้น ระบบการเล่น โหมด และกำหนดการอัปเดตสำหรับผู้เล่นไทย</p>', 'https://picsum.photos/seed/starfall-odyssey/1200/600', 'เกม', '2025-09-11 09:00:00+07'),
  ('ironclad-tactics', 'Ironclad Tactics Tactics-Lite เดือดบนพีซีและคอนโซล', '<p>Ironclad Tactics Tactics-Lite เดือดบนพีซีและคอนโซล — รวมรายละเอียดเบื้องต้น ระบบการเล่น โหมด และกำหนดการอัปเดตสำหรับผู้เล่นไทย</p>', 'https://picsum.photos/seed/ironclad-tactics/1200/600', 'พีซี', '2025-09-12 09:00:00+07'),
  ('kingdoms-reborn-2', 'Kingdoms Reborn II เมืองเติบโตพร้อมระบบการค้าใหม่', '<p>Kingdoms Reborn II เมืองเติบโตพร้อมระบบการค้าใหม่ — รวมรายละเอียดเบื้องต้น ระบบการเล่น โหมด และกำหนดการอัปเดตสำหรับผู้เล่นไทย</p>', 'https://picsum.photos/seed/kingdoms-reborn-2/1200/600', 'เกม', '2025-09-13 09:00:00+07'),
  ('mecha-frontier', 'Mecha Frontier ยิงแหลกหุ่นยักษ์แบบ Co-op 4 คน', '<p>Mecha Frontier ยิงแหลกหุ่นยักษ์แบบ Co-op 4 คน — รวมรายละเอียดเบื้องต้น ระบบการเล่น โหมด และกำหนดการอัปเดตสำหรับผู้เล่นไทย</p>', 'https://picsum.photos/seed/mecha-frontier/1200/600', 'เกมออนไลน์', '2025-09-14 09:00:00+07'),
  ('sakura-chronicles', 'Sakura Chronicles JRPG งานภาพสุดละมุน', '<p>Sakura Chronicles JRPG งานภาพสุดละมุน — รวมรายละเอียดเบื้องต้น ระบบการเล่น โหมด และกำหนดการอัปเดตสำหรับผู้เล่นไทย</p>', 'https://picsum.photos/seed/sakura-chronicles/1200/600', 'คอนโซล', '2025-09-15 09:00:00+07'),
  ('shadowline', 'Shadowline Tactical Shooter โหมดจัดแรงก์พร้อม!', '<p>Shadowline Tactical Shooter โหมดจัดแรงก์พร้อม! — รวมรายละเอียดเบื้องต้น ระบบการเล่น โหมด และกำหนดการอัปเดตสำหรับผู้เล่นไทย</p>', 'https://picsum.photos/seed/shadowline/1200/600', 'พีซี', '2025-09-16 09:00:00+07'),
  ('echoes-of-eden', 'Echoes of Eden แอ็กชัน RPG โลกเปิด', '<p>Echoes of Eden แอ็กชัน RPG โลกเปิด — รวมรายละเอียดเบื้องต้น ระบบการเล่น โหมด และกำหนดการอัปเดตสำหรับผู้เล่นไทย</p>', 'https://picsum.photos/seed/echoes-of-eden/1200/600', 'เกม', '2025-09-17 09:00:00+07'),
  ('nova-strike', 'Nova Strike ชูตติ้งไซไฟมุมมองด้านบน', '<p>Nova Strike ชูตติ้งไซไฟมุมมองด้านบน — รวมรายละเอียดเบื้องต้น ระบบการเล่น โหมด และกำหนดการอัปเดตสำหรับผู้เล่นไทย</p>', 'https://picsum.photos/seed/nova-strike/1200/600', 'พีซี', '2025-09-18 09:00:00+07'),
  ('legend-of-dragons', 'Legend of Dragons ปลุกตำนานมังกรครั้งใหม่', '<p>Legend of Dragons ปลุกตำนานมังกรครั้งใหม่ — รวมรายละเอียดเบื้องต้น ระบบการเล่น โหมด และกำหนดการอัปเดตสำหรับผู้เล่นไทย</p>', 'https://picsum.photos/seed/legend-of-dragons/1200/600', 'เกม', '2025-09-19 09:00:00+07'),
  ('pixel-racers', 'Pixel Racers แข่งรถ 2D เล่นเพลินทุกวัย', '<p>Pixel Racers แข่งรถ 2D เล่นเพลินทุกวัย — รวมรายละเอียดเบื้องต้น ระบบการเล่น โหมด และกำหนดการอัปเดตสำหรับผู้เล่นไทย</p>', 'https://picsum.photos/seed/pixel-racers/1200/600', 'เกมอินดี้', '2025-09-20 09:00:00+07'),
  ('ocean-quest', 'Ocean Quest ผจญภัยกลางท้องทะเลลึก', '<p>Ocean Quest ผจญภัยกลางท้องทะเลลึก — รวมรายละเอียดเบื้องต้น ระบบการเล่น โหมด และกำหนดการอัปเดตสำหรับผู้เล่นไทย</p>', 'https://picsum.photos/seed/ocean-quest/1200/600', 'เกม', '2025-09-21 09:00:00+07'),
  ('cyberbeat', 'CyberBeat เกมดนตรีไซเบอร์พังก์', '<p>CyberBeat เกมดนตรีไซเบอร์พังก์ — รวมรายละเอียดเบื้องต้น ระบบการเล่น โหมด และกำหนดการอัปเดตสำหรับผู้เล่นไทย</p>', 'https://picsum.photos/seed/cyberbeat/1200/600', 'พีซี', '2025-09-22 09:00:00+07'),
  ('mystic-valley', 'Mystic Valley ฟาร์มมิ่ง & ไลฟ์ซิม', '<p>Mystic Valley ฟาร์มมิ่ง & ไลฟ์ซิม — รวมรายละเอียดเบื้องต้น ระบบการเล่น โหมด และกำหนดการอัปเดตสำหรับผู้เล่นไทย</p>', 'https://picsum.photos/seed/mystic-valley/1200/600', 'เกม', '2025-09-23 09:00:00+07'),
  ('arcane-arena', 'Arcane Arena MOBA แนวเวทมนตร์', '<p>Arcane Arena MOBA แนวเวทมนตร์ — รวมรายละเอียดเบื้องต้น ระบบการเล่น โหมด และกำหนดการอัปเดตสำหรับผู้เล่นไทย</p>', 'https://picsum.photos/seed/arcane-arena/1200/600', 'เกมออนไลน์', '2025-09-24 09:00:00+07'),
  ('steel-horizon', 'Steel Horizon กลยุทธ์เรือรบเรียลไทม์', '<p>Steel Horizon กลยุทธ์เรือรบเรียลไทม์ — รวมรายละเอียดเบื้องต้น ระบบการเล่น โหมด และกำหนดการอัปเดตสำหรับผู้เล่นไทย</p>', 'https://picsum.photos/seed/steel-horizon/1200/600', 'พีซี', '2025-09-25 09:00:00+07'),
  ('forest-spirits', 'Forest Spirits ผจญภัยอินดี้อบอุ่นหัวใจ', '<p>Forest Spirits ผจญภัยอินดี้อบอุ่นหัวใจ — รวมรายละเอียดเบื้องต้น ระบบการเล่น โหมด และกำหนดการอัปเดตสำหรับผู้เล่นไทย</p>', 'https://picsum.photos/seed/forest-spirits/1200/600', 'เกมอินดี้', '2025-09-26 09:00:00+07'),
  ('rift-runners', 'Rift Runners โร๊คไลต์ยิงไว', '<p>Rift Runners โร๊คไลต์ยิงไว — รวมรายละเอียดเบื้องต้น ระบบการเล่น โหมด และกำหนดการอัปเดตสำหรับผู้เล่นไทย</p>', 'https://picsum.photos/seed/rift-runners/1200/600', 'พีซี', '2025-09-27 09:00:00+07'),
  ('last-bastion', 'Last Bastion ป้องกันฐานสไตล์ Tower Defense', '<p>Last Bastion ป้องกันฐานสไตล์ Tower Defense — รวมรายละเอียดเบื้องต้น ระบบการเล่น โหมด และกำหนดการอัปเดตสำหรับผู้เล่นไทย</p>', 'https://picsum.photos/seed/last-bastion/1200/600', 'เกม', '2025-09-28 09:00:00+07'),
  ('neon-drift', 'Neon Drift ขับรถดริฟต์สไตล์เรโทร', '<p>Neon Drift ขับรถดริฟต์สไตล์เรโทร — รวมรายละเอียดเบื้องต้น ระบบการเล่น โหมด และกำหนดการอัปเดตสำหรับผู้เล่นไทย</p>', 'https://picsum.photos/seed/neon-drift/1200/600', 'คอนโซล', '2025-09-29 09:00:00+07'),
  ('battle-cuisine', 'Battle Cuisine ทำอาหารต่อสู้สุดฮา', '<p>Battle Cuisine ทำอาหารต่อสู้สุดฮา — รวมรายละเอียดเบื้องต้น ระบบการเล่น โหมด และกำหนดการอัปเดตสำหรับผู้เล่นไทย</p>', 'https://picsum.photos/seed/battle-cuisine/1200/600', 'เกมอินดี้', '2025-09-30 09:00:00+07'),
  ('windbound-saga', 'Windbound Saga เอาชีวิตรอดบนเกาะลมแรง', '<p>Windbound Saga เอาชีวิตรอดบนเกาะลมแรง — รวมรายละเอียดเบื้องต้น ระบบการเล่น โหมด และกำหนดการอัปเดตสำหรับผู้เล่นไทย</p>', 'https://picsum.photos/seed/windbound-saga/1200/600', 'เกม', '2025-10-01 09:00:00+07'),
  ('crystal-tactics', 'Crystal Tactics วางแผนผลัดเทิร์นลึกแต่เล่นง่าย', '<p>Crystal Tactics วางแผนผลัดเทิร์นลึกแต่เล่นง่าย — รวมรายละเอียดเบื้องต้น ระบบการเล่น โหมด และกำหนดการอัปเดตสำหรับผู้เล่นไทย</p>', 'https://picsum.photos/seed/crystal-tactics/1200/600', 'พีซี', '2025-10-02 09:00:00+07'),
  ('dragon-rider', 'Dragon Rider ขี่มังกรตะลุยดันเจียน', '<p>Dragon Rider ขี่มังกรตะลุยดันเจียน — รวมรายละเอียดเบื้องต้น ระบบการเล่น โหมด และกำหนดการอัปเดตสำหรับผู้เล่นไทย</p>', 'https://picsum.photos/seed/dragon-rider/1200/600', 'เกม', '2025-10-03 09:00:00+07'),
  ('stellar-farm', 'Stellar Farm ทำฟาร์มบนอวกาศ', '<p>Stellar Farm ทำฟาร์มบนอวกาศ — รวมรายละเอียดเบื้องต้น ระบบการเล่น โหมด และกำหนดการอัปเดตสำหรับผู้เล่นไทย</p>', 'https://picsum.photos/seed/stellar-farm/1200/600', 'เกมอินดี้', '2025-10-04 09:00:00+07'),
  ('moonblade', 'Moonblade แอ็กชันดาบรวดเร็ว', '<p>Moonblade แอ็กชันดาบรวดเร็ว — รวมรายละเอียดเบื้องต้น ระบบการเล่น โหมด และกำหนดการอัปเดตสำหรับผู้เล่นไทย</p>', 'https://picsum.photos/seed/moonblade/1200/600', 'คอนโซล', '2025-10-05 09:00:00+07'),
  ('aero-knights', 'Aero Knights ยิงเครื่องบินสงครามแฟนตาซี', '<p>Aero Knights ยิงเครื่องบินสงครามแฟนตาซี — รวมรายละเอียดเบื้องต้น ระบบการเล่น โหมด และกำหนดการอัปเดตสำหรับผู้เล่นไทย</p>', 'https://picsum.photos/seed/aero-knights/1200/600', 'พีซี', '2025-10-06 09:00:00+07'),
  ('dungeon-chef', 'Dungeon Chef ทำอาหารจากมอนสเตอร์', '<p>Dungeon Chef ทำอาหารจากมอนสเตอร์ — รวมรายละเอียดเบื้องต้น ระบบการเล่น โหมด และกำหนดการอัปเดตสำหรับผู้เล่นไทย</p>', 'https://picsum.photos/seed/dungeon-chef/1200/600', 'เกมอินดี้', '2025-10-07 09:00:00+07'),
  ('ghost-hunters', 'Ghost Hunters ล่าผีแบบ Co-op', '<p>Ghost Hunters ล่าผีแบบ Co-op — รวมรายละเอียดเบื้องต้น ระบบการเล่น โหมด และกำหนดการอัปเดตสำหรับผู้เล่นไทย</p>', 'https://picsum.photos/seed/ghost-hunters/1200/600', 'เกมออนไลน์', '2025-10-08 09:00:00+07'),
  ('rune-architect', 'Rune Architect สร้างเมืองด้วยเวทมนตร์', '<p>Rune Architect สร้างเมืองด้วยเวทมนตร์ — รวมรายละเอียดเบื้องต้น ระบบการเล่น โหมด และกำหนดการอัปเดตสำหรับผู้เล่นไทย</p>', 'https://picsum.photos/seed/rune-architect/1200/600', 'เกม', '2025-10-09 09:00:00+07'),
  ('meadow-life', 'Meadow Life ชีวิตชนบทสโลว์ไลฟ์', '<p>Meadow Life ชีวิตชนบทสโลว์ไลฟ์ — รวมรายละเอียดเบื้องต้น ระบบการเล่น โหมด และกำหนดการอัปเดตสำหรับผู้เล่นไทย</p>', 'https://picsum.photos/seed/meadow-life/1200/600', 'เกม', '2025-10-10 09:00:00+07')
ON CONFLICT (slug) DO NOTHING;

-- อัปเดต home_config: hero/ticker/grid ดึงจาก DB
UPDATE home_config
SET data = jsonb_set(
            jsonb_set(
              jsonb_set(COALESCE(data,'{}'::jsonb), '{hero}',
                jsonb_build_object(
                  'img','https://picsum.photos/seed/hero/1280/640',
                  'cat','กำลังฮิต',
                  'title','หัวข้อเด่นประจำวัน'
                ), true),
              '{ticker}', to_jsonb(ARRAY[
                'เปิดตัวเกมใหม่เพียบ ต้นเดือนนี้',
                'อัปเดตใหญ่หลายเกมดัง',
                'รวมเกมอินดี้น่าเล่นสุดสัปดาห์'
              ]), true),
            '{grid}', to_jsonb(ARRAY[
                jsonb_build_object('slug','starfall-odyssey','title','Starfall Odyssey เปิดตัวเกม RPG แฟนตาซีอวกาศ','image','https://picsum.photos/seed/starfall-odyssey/800/450','badge','เกม','date','2025-10-05'),
                jsonb_build_object('slug','ironclad-tactics','title','Ironclad Tactics Tactics-Lite เดือดบนพีซีและคอนโซล','image','https://picsum.photos/seed/ironclad-tactics/800/450','badge','พีซี','date','2025-10-06'),
                jsonb_build_object('slug','kingdoms-reborn-2','title','Kingdoms Reborn II เมืองเติบโตพร้อมระบบการค้าใหม่','image','https://picsum.photos/seed/kingdoms-reborn-2/800/450','badge','เกม','date','2025-10-07'),
                jsonb_build_object('slug','mecha-frontier','title','Mecha Frontier ยิงแหลกหุ่นยักษ์แบบ Co-op 4 คน','image','https://picsum.photos/seed/mecha-frontier/800/450','badge','เกมออนไลน์','date','2025-10-08'),
                jsonb_build_object('slug','sakura-chronicles','title','Sakura Chronicles JRPG งานภาพสุดละมุน','image','https://picsum.photos/seed/sakura-chronicles/800/450','badge','คอนโซล','date','2025-10-09'),
                jsonb_build_object('slug','shadowline','title','Shadowline Tactical Shooter โหมดจัดแรงก์พร้อม!','image','https://picsum.photos/seed/shadowline/800/450','badge','พีซี','date','2025-10-10')
              ]), true
          ),
    updated_at = now()
WHERE id = 1;
